// GENERATED by scripts/gen-mirror.mjs from @open-mercato/core@0.7.0 (lib/queue-policy.ts). Do not edit.
// This package mirrors core's data_sync module file-for-file; see docs/adr/0006-drop-in-data-sync.md.
export * from '@open-mercato/core/modules/data_sync/lib/queue-policy'
export { DATA_SYNC_EXPORT_QUEUE, DATA_SYNC_IMPORT_QUEUE, DATA_SYNC_LOCK_DURATION_MS, DATA_SYNC_MAX_STALLED_COUNT, DATA_SYNC_QUEUE_ATTEMPTS, DATA_SYNC_RESUMABLE_QUEUES } from '@open-mercato/core/modules/data_sync/lib/queue-policy'
