// GENERATED by scripts/gen-mirror.mjs from @open-mercato/core@0.7.0 (lib/sync-engine.ts). Do not edit.
// This package mirrors core's data_sync module file-for-file; see docs/adr/0006-drop-in-data-sync.md.
export * from '@open-mercato/core/modules/data_sync/lib/sync-engine'
export { createSyncEngine } from '@open-mercato/core/modules/data_sync/lib/sync-engine'
