approvedGitRepositories:
  - "**"

compressionLevel: mixed

enableScripts: true

enableTelemetry: false

nodeLinker: node-modules

npmMinimalAgeGate: 0

npmPreapprovedPackages:
  - "@open-mercato/*"

npmPublishRegistry: "https://registry.npmjs.org"

npmRegistryServer: "https://registry.npmjs.org"
