'use client'
// GENERATED by scripts/gen-mirror.mjs from @open-mercato/core@0.7.0 (backend/data-sync/runs/[id]/page.tsx). Do not edit.
// This package mirrors core's data_sync module file-for-file; see docs/adr/0006-drop-in-data-sync.md.
export * from '@open-mercato/core/modules/data_sync/backend/data-sync/runs/[id]/page'
export { default } from '@open-mercato/core/modules/data_sync/backend/data-sync/runs/[id]/page'
