// GENERATED by scripts/gen-mirror.mjs from @open-mercato/core@0.7.0 (api/runs/[id]/retry.ts). Do not edit.
// This package mirrors core's data_sync module file-for-file; see docs/adr/0006-drop-in-data-sync.md.
export * from '@open-mercato/core/modules/data_sync/api/runs/[id]/retry'
export { POST } from '@open-mercato/core/modules/data_sync/api/runs/[id]/retry'
import { openApi as coreOpenApi } from '@open-mercato/core/modules/data_sync/api/runs/[id]/retry'
export const openApi = coreOpenApi
// Copied from core: the generator reads this by AST and cannot follow a re-export.
export const metadata = {
  POST: { requireAuth: true, requireFeatures: ['data_sync.run'] },
}
