#!/usr/bin/env node
// Generates src/modules/data_sync/** as a mirror of core's data_sync module.
//
// This package is a DROP-IN for `@open-mercato/core`'s `data_sync` module: the host
// registers `{ id: 'data_sync', from: '@fullstackhouse/open-mercato-data-sync-durable' }`
// and the OM CLI loads our `modules/data_sync/` tree instead of core's. Every file we
// do not deliberately replace is a generated stub that re-exports core's file, so the
// surface (routes, pages, ACL, entities, migrations, i18n, events) stays byte-for-byte
// core's for the pinned core version. See docs/adr/0006-drop-in-data-sync.md.
//
//   node scripts/gen-mirror.mjs           # (re)generate stubs + manifest
//   node scripts/gen-mirror.mjs --check   # exit 1 if stubs/manifest are stale (CI, prebuild)
//
// Files listed in mirror.replaced.json are ours and never overwritten; for those the
// manifest records the hash of the core file they replace, so --check flags when core
// changed something we forked ("review the replacement against core").
import { createHash } from 'node:crypto'
import { existsSync, mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs'
import { createRequire } from 'node:module'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import ts from 'typescript'

const pkgDir = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const require = createRequire(path.join(pkgDir, 'package.json'))
const check = process.argv.includes('--check')

const MODULE_ID = 'data_sync'
const CORE_IMPORT_BASE = `@open-mercato/core/modules/${MODULE_ID}`
const OUT_DIR = path.join(pkgDir, 'src', 'modules', MODULE_ID)
const MANIFEST_PATH = path.join(pkgDir, 'src', 'mirror.manifest.json')
// The OM CLI reads a package-backed module's entity ids and field names from
// `<pkgRoot>/generated` (falling back to `<pkgRoot>/dist/generated`) — see
// `loadStandaloneGeneratedPackageEntities` in @open-mercato/cli's entity-ids generator.
// That escape hatch is how a mirror ships entity metadata its stubs cannot express.
const GENERATED_DIR = path.join(pkgDir, 'generated')
const REPLACED_PATH = path.join(pkgDir, 'mirror.replaced.json')
const SKIP_DIRS = new Set(['__tests__', '__integration__', '__mocks__', 'node_modules'])
const SKIP_FILES = /(\.test\.tsx?|\.spec\.tsx?|AGENTS\.md|README\.md)$/

// `@open-mercato/core`'s exports map rewrites `./*.json` to `./src/*.json`, so
// `require.resolve('@open-mercato/core/package.json')` does NOT reach the manifest.
// Resolve the entry point instead and walk up to the package root.
function corePackageRoot() {
  let dir = path.dirname(require.resolve('@open-mercato/core'))
  for (;;) {
    const manifest = path.join(dir, 'package.json')
    if (existsSync(manifest)) {
      try {
        if (JSON.parse(readFileSync(manifest, 'utf8')).name === '@open-mercato/core') return dir
      } catch {
        /* keep walking */
      }
    }
    const parent = path.dirname(dir)
    if (parent === dir) throw new Error('gen-mirror: could not locate the @open-mercato/core package root')
    dir = parent
  }
}

const coreRoot = corePackageRoot()
const coreVersion = JSON.parse(readFileSync(path.join(coreRoot, 'package.json'), 'utf8')).version
const coreSrcRoot = path.join(coreRoot, 'src', 'modules', MODULE_ID)
if (!existsSync(coreSrcRoot)) {
  console.error(`gen-mirror: core sources not found at ${coreSrcRoot} (does the installed @open-mercato/core ship src/?)`)
  process.exit(2)
}

const replaced = new Set(existsSync(REPLACED_PATH) ? JSON.parse(readFileSync(REPLACED_PATH, 'utf8')).files : [])
const sha = (buf) => createHash('sha256').update(buf).digest('hex').slice(0, 16)

function walk(dir, rel = '') {
  const out = []
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const relPath = rel ? `${rel}/${entry.name}` : entry.name
    if (entry.isDirectory()) {
      if (!SKIP_DIRS.has(entry.name)) out.push(...walk(path.join(dir, entry.name), relPath))
      continue
    }
    if (SKIP_FILES.test(entry.name)) continue
    out.push(relPath)
  }
  return out.sort()
}

const HEADER = (rel) =>
  `// GENERATED by scripts/gen-mirror.mjs from @open-mercato/core@${coreVersion} (${rel}). Do not edit.\n` +
  `// This package mirrors core's data_sync module file-for-file; see docs/adr/0006-drop-in-data-sync.md.\n`

// The OM generator decides whether an api/ file is a route — and which methods it serves —
// by REGEX over the file's own text (`detectExportedHttpMethods` in @open-mercato/cli's
// module-registry generator). `export * from …` is invisible to it, so a pure star stub
// registers zero routes. Naming the methods explicitly is what makes the stub a route file;
// the generator's own re-export branch (`export { GET, POST } from …`) matches this shape.
// Everything else it needs (metadata, openApi) it reads by importing the module, which does
// follow the star. Verified against core@0.7.0: 11 data_sync routes, identical to core's.
const HTTP_METHODS = ['GET', 'POST', 'PUT', 'PATCH', 'DELETE']

function exportedHttpMethods(source) {
  const found = new Set()
  for (const method of HTTP_METHODS) {
    if (new RegExp(`export\\s+(?:async\\s+)?function\\s+${method}\\b|export\\s+(?:const|let|var)\\s+${method}\\b`).test(source)) {
      found.add(method)
    }
  }
  for (const match of source.matchAll(/export\s*\{([^}]+)\}/g)) {
    for (const part of (match[1] ?? '').split(',')) {
      const name = part.trim().split(/\s+as\s+/i).pop()?.trim()
      if (name && HTTP_METHODS.includes(name)) found.add(name)
    }
  }
  return HTTP_METHODS.filter((m) => found.has(m))
}

// The route generator reads a route's `metadata` (auth + required ACL features) by AST,
// not by importing the module — `extractNamedObjectLiteralExport`, with a dynamic-import
// fallback that cannot work for a source file under node_modules. A star stub therefore
// yields `metadata: undefined` on the runtime route table, i.e. a route that silently
// loses its `requireAuth` / `requireFeatures`. So the literal is copied verbatim.
// `openApi` only needs to be SEEN (its value is read from the namespace at runtime), so
// an alias re-export is enough there.
function copiedObjectLiteralExport(source, exportName) {
  const sf = ts.createSourceFile(`${exportName}.ts`, source, ts.ScriptTarget.Latest, true, ts.ScriptKind.TS)
  for (const statement of sf.statements) {
    if (!ts.isVariableStatement(statement)) continue
    if (!statement.modifiers?.some((m) => m.kind === ts.SyntaxKind.ExportKeyword)) continue
    for (const declaration of statement.declarationList.declarations) {
      if (!ts.isIdentifier(declaration.name) || declaration.name.text !== exportName) continue
      let initializer = declaration.initializer
      while (initializer && (ts.isAsExpression(initializer) || ts.isParenthesizedExpression(initializer))) {
        initializer = initializer.expression
      }
      if (!initializer || !ts.isObjectLiteralExpression(initializer)) return null
      // Only self-contained literals can be copied; anything referencing an import
      // would not have been readable by the generator for core either.
      const text = declaration.initializer.getText(sf)
      return /\b(?:require|import)\b/.test(text) ? null : text
    }
  }
  return null
}

function stubFor(rel, source) {
  const noExt = rel.replace(/\.(tsx?|mjs|js)$/, '')
  const target = `${CORE_IMPORT_BASE}/${noExt}`
  const useClient = /^\s*(['"])use client\1/.test(source)
  const hasDefault = /export\s+default\b/.test(source) || /export\s*\{[^}]*\bdefault\b[^}]*\}/.test(source)
  const isApi = rel.startsWith('api/')
  // Explicit named exports shadow the star for the same name, so both may coexist.
  const methods = isApi ? exportedHttpMethods(source) : []
  const metadata = isApi && methods.length ? copiedObjectLiteralExport(source, 'metadata') : null
  const hasOpenApi = isApi && methods.length && /export\s+(?:const|let|var)\s+openApi\b/.test(source)
  if (isApi && methods.length && !metadata && /export\s+(?:const|let|var)\s+metadata\b/.test(source)) {
    console.warn(`gen-mirror: ${rel} exports a non-literal \`metadata\`; the route will fall back to auth-required defaults`)
  }
  return (
    (useClient ? `'use client'\n` : '') +
    HEADER(rel) +
    `export * from '${target}'\n` +
    (hasDefault ? `export { default } from '${target}'\n` : '') +
    (methods.length ? `export { ${methods.join(', ')} } from '${target}'\n` : '') +
    (hasOpenApi ? `import { openApi as coreOpenApi } from '${target}'\nexport const openApi = coreOpenApi\n` : '') +
    (metadata ? `// Copied from core: the generator reads this by AST and cannot follow a re-export.\nexport const metadata = ${metadata}\n` : '')
  )
}

// ---------------------------------------------------------------------------
// Entity descriptor (`generated/`)
//
// `data/entities.ts` is a star stub on purpose: the app's `entities.generated.ts`
// spreads our namespace, so MikroORM registers CORE's actual entity classes and
// class identity is preserved for every core service that queries them. The cost is
// that the CLI's entity-id generator reads classes from the file's AST, which a stub
// has none of — so `E.data_sync` would come out empty. We fill it by emitting the
// package-level `generated/` descriptor the CLI looks for, parsed from core's real
// entities file with the same rules the CLI uses (`parseExportedClassNamesFromFile`
// / `parseEntityFieldsFromFile` / `toSnake` in @open-mercato/cli).
const toSnake = (s) =>
  s
    .replace(/([a-z0-9])([A-Z])/g, '$1_$2')
    .replace(/\W+/g, '_')
    .replace(/_{2,}/g, '_')
    .replace(/(?:^_+|_+$)/g, '')
    .toLowerCase()

function decoratorNameOverride(decorator) {
  const expr = decorator.expression
  if (!ts.isCallExpression(expr) || !expr.arguments.length) return undefined
  const first = expr.arguments[0]
  if (!ts.isObjectLiteralExpression(first)) return undefined
  for (const prop of first.properties) {
    if (ts.isPropertyAssignment(prop) && ts.isIdentifier(prop.name) && prop.name.text === 'name') {
      if (ts.isStringLiteral(prop.initializer)) return prop.initializer.text
    }
  }
  return undefined
}

function parseCoreEntities(absPath) {
  const sf = ts.createSourceFile(absPath, readFileSync(absPath, 'utf8'), ts.ScriptTarget.ES2020, true, ts.ScriptKind.TS)
  const byEntity = {}
  sf.forEachChild((node) => {
    if (!ts.isClassDeclaration(node) || !node.name) return
    if (!node.modifiers?.some((m) => m.kind === ts.SyntaxKind.ExportKeyword)) return
    const fields = []
    for (const member of node.members) {
      if (!ts.isPropertyDeclaration(member) || !member.name) continue
      const propName = ts.isIdentifier(member.name) || ts.isStringLiteral(member.name) ? member.name.text : undefined
      if (!propName) continue
      if (member.modifiers?.some((m) => m.kind === ts.SyntaxKind.StaticKeyword)) continue
      const decorators = ts.canHaveDecorators(member) ? ts.getDecorators(member) ?? [] : []
      let dbName
      for (const decorator of decorators) {
        const override = decoratorNameOverride(decorator)
        dbName = override ?? toSnake(propName)
        break
      }
      fields.push(dbName ?? toSnake(propName))
    }
    byEntity[toSnake(node.name.text)] = [...new Set(fields)]
  })
  return byEntity
}

function entityDescriptorFiles() {
  const entitiesFile = path.join(coreSrcRoot, 'data', 'entities.ts')
  if (!existsSync(entitiesFile)) return new Map()
  const byEntity = parseCoreEntities(entitiesFile)
  const files = new Map()
  const ids = { [MODULE_ID]: Object.fromEntries(Object.keys(byEntity).map((e) => [e, `${MODULE_ID}:${e}`])) }
  files.set(
    'entities.ids.generated.ts',
    `// GENERATED by scripts/gen-mirror.mjs from @open-mercato/core@${coreVersion} (data/entities.ts). Do not edit.\n` +
      `// Read by the Open Mercato CLI for a package-backed module whose entities file is a re-export stub.\n` +
      `export const M = ${JSON.stringify({ [MODULE_ID]: MODULE_ID }, null, 2)} as const\n` +
      `export const E = ${JSON.stringify(ids, null, 2)} as const\n`,
  )
  for (const [entity, fields] of Object.entries(byEntity)) {
    files.set(
      path.join('entities', entity, 'index.ts'),
      fields.map((f) => `export const ${f} = ${JSON.stringify(f)};`).join('\n') + '\n',
    )
  }
  return files
}

const coreFiles = walk(coreSrcRoot)
const manifest = { coreVersion, moduleId: MODULE_ID, generated: {}, replaced: {}, entityDescriptor: [] }
const planned = new Map() // out rel path -> content (string | Buffer)

for (const rel of coreFiles) {
  const abs = path.join(coreSrcRoot, rel)
  const buf = readFileSync(abs)
  if (replaced.has(rel)) {
    manifest.replaced[rel] = sha(buf) // hash of the CORE file our replacement shadows
    continue
  }
  if (rel.endsWith('.json')) {
    planned.set(rel, buf)
  } else if (/\.(ts|tsx)$/.test(rel)) {
    planned.set(rel, stubFor(rel, buf.toString('utf8')))
  } else {
    continue // .md and anything else is not part of the module contract
  }
  manifest.generated[rel] = sha(buf)
}

// Replaced files must exist on our side.
const missing = [...replaced].filter((rel) => !existsSync(path.join(OUT_DIR, rel)))
if (missing.length) {
  console.error(`gen-mirror: mirror.replaced.json lists files that do not exist under src/modules/${MODULE_ID}:\n  ${missing.join('\n  ')}`)
  process.exit(2)
}

const plannedGenerated = entityDescriptorFiles()
for (const rel of plannedGenerated.keys()) manifest.entityDescriptor.push(rel)

const manifestText = JSON.stringify(manifest, null, 2) + '\n'

if (check) {
  const problems = []
  if (!existsSync(MANIFEST_PATH)) problems.push('mirror.manifest.json is missing')
  else {
    const current = JSON.parse(readFileSync(MANIFEST_PATH, 'utf8'))
    if (current.coreVersion !== coreVersion) problems.push(`manifest was generated from core@${current.coreVersion}, installed is ${coreVersion}`)
    for (const [rel, h] of Object.entries(manifest.generated)) {
      if (current.generated?.[rel] !== h) problems.push(`stale or missing stub: ${rel}`)
    }
    for (const rel of Object.keys(current.generated ?? {})) {
      if (!(rel in manifest.generated) && !replaced.has(rel)) problems.push(`stub no longer in core: ${rel}`)
    }
    for (const [rel, h] of Object.entries(manifest.replaced)) {
      if (current.replaced?.[rel] !== h) problems.push(`REPLACED file changed upstream — review src/modules/${MODULE_ID}/${rel} against core: ${rel}`)
    }
  }
  for (const [dir, files] of [[OUT_DIR, planned], [GENERATED_DIR, plannedGenerated]]) {
    for (const [rel, content] of files) {
      const out = path.join(dir, rel)
      if (!existsSync(out)) { problems.push(`missing generated file: ${path.relative(pkgDir, out)}`); continue }
      const onDisk = readFileSync(out)
      const same = Buffer.isBuffer(content) ? onDisk.equals(content) : onDisk.toString('utf8') === content
      if (!same) problems.push(`generated file differs from what core@${coreVersion} would produce: ${path.relative(pkgDir, out)}`)
    }
  }
  if (problems.length) {
    console.error(`gen-mirror --check: ${problems.length} problem(s)\n  ${problems.join('\n  ')}\nRun: yarn gen:mirror`)
    process.exit(1)
  }
  console.log(`gen-mirror --check: mirror of core@${coreVersion} is current (${planned.size} generated, ${replaced.size} replaced, ${plannedGenerated.size} entity-descriptor)`)
  process.exit(0)
}

// Regenerate: remove previously generated files (never the replaced ones), then write.
if (existsSync(OUT_DIR)) {
  for (const rel of walk(OUT_DIR)) {
    if (replaced.has(rel)) continue
    const abs = path.join(OUT_DIR, rel)
    const head = readFileSync(abs, 'utf8').slice(0, 400)
    const isGenerated = head.includes('GENERATED by scripts/gen-mirror.mjs') || rel.endsWith('.json')
    if (isGenerated && !planned.has(rel)) rmSync(abs)
  }
}
if (existsSync(GENERATED_DIR)) rmSync(GENERATED_DIR, { recursive: true })
for (const [dir, files] of [[OUT_DIR, planned], [GENERATED_DIR, plannedGenerated]]) {
  for (const [rel, content] of files) {
    const out = path.join(dir, rel)
    mkdirSync(path.dirname(out), { recursive: true })
    writeFileSync(out, content)
  }
}
writeFileSync(MANIFEST_PATH, manifestText)
console.log(
  `gen-mirror: mirrored core@${coreVersion} ${MODULE_ID} → ${planned.size} generated files, ` +
    `${replaced.size} replaced, ${plannedGenerated.size} entity-descriptor files (manifest updated)`,
)
