#!/bin/bash
# The one-time bootstrap that automation cannot do for itself.
#
#   ./scripts/bootstrap-release.sh
#
# npm cannot create a package over OIDC — a trusted publisher can only be configured on a
# package that already exists — so each package needs one publish from a real terminal. npm
# also masks the 2FA approval URL in both its output and its debug log, deliberately, so this
# genuinely has to be run by a person with a browser. Everything either side of that is here.
#
# Run it from a terminal you can see, on a clean main. It is safe to re-run: every step checks
# whether it has already happened.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

REPO="fullstackhouse/open-mercato-durable"
WORKFLOW="ci.yml"
MECHANISM="@fullstackhouse/open-mercato-durable-work"
ADOPTER="@fullstackhouse/open-mercato-data-sync-durable"

step()  { printf '\n\033[1m▸ %s\033[0m\n' "$1"; }
pass()  { printf '\033[32m  ✓ %s\033[0m\n' "$1"; }
skip()  { printf '\033[90m  – %s\033[0m\n' "$1"; }
fail()  { printf '\033[31m  ✗ %s\033[0m\n' "$1" >&2; exit 1; }

published() { npm view "$1" version --registry https://registry.npmjs.org > /dev/null 2>&1; }

# Publishing is confirmed by asking the registry, not by trusting the exit code.
#
# `npm publish` has been observed exiting 0, in under a second, having published nothing: a
# mistyped flag was enough (`--provenance=false` parses as the boolean flag plus a stray
# positional; the negation is `--no-provenance`). The script then went on to hand publishing
# rights to a package that did not exist, and the confusing error surfaced there rather than at
# the step that actually failed. A command's opinion of itself is not evidence.
confirm_published() {
  local package="$1"
  local attempt
  for attempt in 1 2 3 4 5 6 7 8 9 10; do
    if published "$package"; then
      pass "$package@$(npm view "$package" version) is on the registry"
      return 0
    fi
    sleep 3
  done
  fail "$package is still not on the registry. Nothing was published - read the publish output above."
}

step "Checks"
[ -z "$(git status --porcelain)" ] || fail "working tree is not clean"
[ "$(git rev-parse --abbrev-ref HEAD)" = "main" ] || fail "not on main"
git fetch origin --quiet
[ "$(git rev-list --count HEAD..origin/main)" = "0" ] || fail "behind origin/main — pull first"
npm whoami --registry https://registry.npmjs.org > /dev/null 2>&1 \
  || fail "not logged in to npm. Run: npm login --auth-type=web --scope=@fullstackhouse"
pass "clean main, logged in as $(npm whoami --registry https://registry.npmjs.org)"

VERSION="$(node -p "require('$ROOT/packages/durable-work/package.json').version")"
OTHER="$(node -p "require('$ROOT/packages/data-sync-durable/package.json').version")"
[ "$VERSION" = "$OTHER" ] || fail "the two packages disagree on the version ($VERSION vs $OTHER); they release in lockstep"
pass "both packages at $VERSION"

step "Proving the published shape works before publishing it"
# A version number can never be reused, so this runs first rather than after.
./scripts/install-lane.sh latest > /tmp/bootstrap-install-lane.log 2>&1 \
  || { tail -20 /tmp/bootstrap-install-lane.log >&2; fail "install lane failed — not publishing"; }
pass "install lane green"

# `--no-provenance` for these two publishes only. Provenance is generated by the CI provider and
# cannot be produced from a laptop, so `publishConfig.provenance: true` — which is what we want
# for every automated release — makes a manual publish fail outright. Every release after this
# one carries provenance.
#
# The spelling matters: `--provenance=false` parses as the boolean flag plus a stray positional,
# and npm then exits 0 having published nothing at all.
step "Publishing $MECHANISM@$VERSION"
if published "$MECHANISM"; then
  skip "already on npm ($(npm view "$MECHANISM" version))"
else
  echo "  npm will open a browser for 2FA — approve it there."
  (cd packages/durable-work && npm publish --no-provenance) || fail "publish failed"
  confirm_published "$MECHANISM"
fi

# The mechanism first, always: the adopter peer-depends on ^$VERSION, and a peer range that
# cannot be satisfied is a broken install for anyone who takes the adopter alone.
step "Publishing $ADOPTER@$VERSION"
if published "$ADOPTER"; then
  skip "already on npm ($(npm view "$ADOPTER" version))"
else
  (cd packages/data-sync-durable && npm publish --no-provenance) || fail "publish failed"
  confirm_published "$ADOPTER"
fi

step "Handing publishing rights to CI"
# From here npm accepts publishes from this repository's workflow over OIDC, with no token
# stored anywhere.
for package in "$MECHANISM" "$ADOPTER"; do
  # npm answers a bare 400 when the package does not exist, which reads as a problem with the
  # trust configuration rather than with the publish that never happened.
  published "$package" || fail "$package is not on npm yet, so it cannot have a trusted publisher. Publish it first."
  if npm trust github "$package" --file "$WORKFLOW" --repo "$REPO" --yes > /tmp/bootstrap-trust.log 2>&1; then
    pass "trusted publisher set for $package"
  else
    if grep -qi "already" /tmp/bootstrap-trust.log; then
      skip "$package already has a trusted publisher"
    else
      tail -10 /tmp/bootstrap-trust.log >&2
      fail "could not configure the trusted publisher for $package"
    fi
  fi
done

step "Tagging, so semantic-release continues from here"
# Not bookkeeping: with no tag on the branch semantic-release computes the first release as
# 1.0.0. The tag is what keeps the line in 0.x.
if git rev-parse "v$VERSION" > /dev/null 2>&1; then
  skip "v$VERSION already exists"
else
  git tag "v$VERSION"
  git push origin "v$VERSION"
  pass "tagged v$VERSION"
fi

step "Turning the release job on"
if [ "$(gh variable get NPM_RELEASE_ENABLED --repo "$REPO" 2>/dev/null || echo)" = "true" ]; then
  skip "NPM_RELEASE_ENABLED is already true"
else
  gh variable set NPM_RELEASE_ENABLED --body true --repo "$REPO"
  pass "NPM_RELEASE_ENABLED=true"
fi

printf '\n\033[32m✓ bootstrap complete — every green merge to main now releases by itself\033[0m\n'
printf '  check what a merge would release:  yarn release:dry-run\n'
